// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { GpsFrame } from './go-pro/gps-frame.js';
export { GpsSample } from './go-pro/gps-sample.js';
export { MetaTrack } from './go-pro/meta-track.js';
export { TrackSample } from './go-pro/track-sample.js';
