[tool.poetry]
name = "gpmfviz"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flatbuffers = "24.3.25"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
